// Generated by scripts/generate-xray-parity-manifest.ts.
// Config: xray-parity.config.ts
// Do not edit this file by hand.

import { getXrayParityRelease, getXrayParityReleases } from "../../src/index.js";

export const selectedGeneratedReleaseTags = [
  "v25.10.15",
  "v26.4.25",
  "v26.5.3",
  "v26.6.22",
  "v26.6.27",
  "v26.7.11",
  "v26.7.28",
  "v26.9.8",
  "v26.9.9"
] as const;
export const selectedGeneratedVersions = [
  "25.10.15",
  "26.4.25",
  "26.5.3",
  "26.6.22",
  "26.6.27",
  "26.7.11",
  "26.7.28",
  "26.9.8",
  "26.9.9"
] as const;
export const selectedGeneratedReleases = getXrayParityReleases();
export const oldestGeneratedRelease = selectedGeneratedReleases[0]!;
export const latestGeneratedRelease = getXrayParityRelease({ releaseTag: "v26.9.9" });
